import type { ManagedUnitRecord } from "@/components/silverpines/types";

export const silverPinesUnits: ManagedUnitRecord[] = [
  {
    unitCode: "SILVER-A-101",
    propertyCode: "SILVER",
    propertyName: "SilverPines",
    buildingLabel: "A",
    floorLabel: "1",
    unitNumber: "101",
    unitKind: "APARTMENT",
    status: "Occupied",
    hasGarage: true,
    garageIndicator: "Y",
    linkedGarageCode: "SILVER-G-01",
    openIssuesCount: 1,
    nextScheduledMaintenance: "2026-04-03",
    lastRepairAt: "2026-03-10",
    lastMaintenanceAt: "2026-02-20",
    ytdRepairCost: 285,
    notesSummary: "Kitchen sink repair completed; follow-up valve inspection pending.",
    repairs: [
      {
        id: "rep-101-1",
        title: "Kitchen sink leak",
        category: "Plumbing",
        priority: "High",
        status: "Completed",
        description: "Replaced worn shutoff valve and resealed under-sink fittings.",
        vendorName: "Uintah Plumbing",
        openedAt: "2026-03-08",
        scheduledFor: "2026-03-09",
        completedAt: "2026-03-10",
        estimatedCost: 250,
        actualCost: 285,
      },
    ],
    maintenance: [
      {
        id: "mnt-101-1",
        title: "Quarterly HVAC filter change",
        category: "HVAC",
        status: "Upcoming",
        dueAt: "2026-04-03",
        vendorName: "Basin Mechanical",
        estimatedCost: 45,
      },
    ],
    accessCodes: [
      {
        id: "acc-101-1",
        label: "Apartment keypad",
        accessType: "ApartmentDoor",
        codeLast4: "9142",
        isActive: true,
        effectiveFrom: "2026-01-01",
      },
      {
        id: "acc-101-2",
        label: "Garage keypad",
        accessType: "GarageDoor",
        codeLast4: "4408",
        isActive: true,
        effectiveFrom: "2026-01-01",
      },
    ],
    keys: [
      {
        id: "key-101-1",
        keyLabel: "Unit entry key",
        keyType: "Physical",
        serialNumber: "SP-A101-01",
        assignedTo: "Tenant set",
        issuedAt: "2026-01-01",
        isActive: true,
      },
    ],
    documents: [
      {
        id: "doc-101-1",
        name: "sink-repair-invoice-mar-2026.pdf",
        category: "Invoice",
        mimeType: "application/pdf",
        uploadedAt: "2026-03-10",
        sizeLabel: "240 KB",
        summary: "Final plumbing invoice.",
      },
      {
        id: "doc-101-2",
        name: "unit-a101-maintenance-log.xlsx",
        category: "Spreadsheet",
        mimeType:
          "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        uploadedAt: "2026-03-11",
        sizeLabel: "88 KB",
        summary: "Running maintenance ledger.",
      },
    ],
    notes: [
      "Tenant reported a brief pressure fluctuation two days before the leak became visible.",
      "Garage assignment confirmed for this apartment.",
    ],
  },
  {
    unitCode: "SILVER-A-102",
    propertyCode: "SILVER",
    propertyName: "SilverPines",
    buildingLabel: "A",
    floorLabel: "1",
    unitNumber: "102",
    unitKind: "APARTMENT",
    status: "Vacant",
    hasGarage: false,
    garageIndicator: "N",
    openIssuesCount: 0,
    nextScheduledMaintenance: "2026-03-29",
    lastRepairAt: "2026-02-14",
    lastMaintenanceAt: "2026-02-28",
    ytdRepairCost: 110,
    notesSummary: "Vacant turn unit. Paint and deep clean already completed.",
    repairs: [
      {
        id: "rep-102-1",
        title: "Bedroom blind replacement",
        category: "Cosmetic",
        priority: "Low",
        status: "Completed",
        openedAt: "2026-02-13",
        completedAt: "2026-02-14",
        actualCost: 110,
      },
    ],
    maintenance: [
      {
        id: "mnt-102-1",
        title: "Move-in readiness inspection",
        category: "Inspection",
        status: "DueSoon",
        dueAt: "2026-03-29",
      },
    ],
    accessCodes: [
      {
        id: "acc-102-1",
        label: "Apartment keypad",
        accessType: "ApartmentDoor",
        codeLast4: "1187",
        isActive: true,
        effectiveFrom: "2026-02-01",
      },
    ],
    keys: [
      {
        id: "key-102-1",
        keyLabel: "Leasing key set",
        keyType: "Physical",
        serialNumber: "SP-A102-01",
        assignedTo: "Office",
        issuedAt: "2026-02-01",
        isActive: true,
      },
    ],
    documents: [],
    notes: ["Ready for showing after inspection clears."],
  },
  {
    unitCode: "SILVER-B-201",
    propertyCode: "SILVER",
    propertyName: "SilverPines",
    buildingLabel: "B",
    floorLabel: "2",
    unitNumber: "201",
    unitKind: "APARTMENT",
    status: "Occupied",
    hasGarage: true,
    garageIndicator: "Y",
    linkedGarageCode: "SILVER-G-02",
    openIssuesCount: 2,
    nextScheduledMaintenance: "2026-03-25",
    lastRepairAt: "2026-03-14",
    lastMaintenanceAt: "2026-01-12",
    ytdRepairCost: 760,
    notesSummary: "Bathroom fan and balcony light both still open.",
    repairs: [
      {
        id: "rep-201-1",
        title: "Bathroom exhaust fan replacement",
        category: "Electrical",
        priority: "Medium",
        status: "Scheduled",
        openedAt: "2026-03-14",
        scheduledFor: "2026-03-21",
        estimatedCost: 300,
      },
      {
        id: "rep-201-2",
        title: "Balcony light intermittent fault",
        category: "Electrical",
        priority: "Low",
        status: "Reported",
        openedAt: "2026-03-15",
        estimatedCost: 120,
      },
    ],
    maintenance: [
      {
        id: "mnt-201-1",
        title: "Smoke detector test",
        category: "Safety",
        status: "DueSoon",
        dueAt: "2026-03-25",
      },
    ],
    accessCodes: [
      {
        id: "acc-201-1",
        label: "Apartment keypad",
        accessType: "ApartmentDoor",
        codeLast4: "5520",
        isActive: true,
        effectiveFrom: "2026-01-01",
      },
    ],
    keys: [
      {
        id: "key-201-1",
        keyLabel: "Emergency master duplicate",
        keyType: "Physical",
        serialNumber: "SP-B201-EM",
        assignedTo: "Maintenance office",
        issuedAt: "2026-01-01",
        isActive: true,
      },
    ],
    documents: [
      {
        id: "doc-201-1",
        name: "b201-electrical-notes.pdf",
        category: "Repair",
        mimeType: "application/pdf",
        uploadedAt: "2026-03-15",
        sizeLabel: "124 KB",
      },
    ],
    notes: ["Resident prefers weekday access after 3 PM."],
  },
  {
    unitCode: "SILVER-B-202",
    propertyCode: "SILVER",
    propertyName: "SilverPines",
    buildingLabel: "B",
    floorLabel: "2",
    unitNumber: "202",
    unitKind: "APARTMENT",
    status: "Occupied",
    hasGarage: false,
    garageIndicator: "N",
    openIssuesCount: 0,
    nextScheduledMaintenance: "2026-05-01",
    lastRepairAt: "2026-01-05",
    lastMaintenanceAt: "2026-02-01",
    ytdRepairCost: 95,
    notesSummary: "No active issues.",
    repairs: [
      {
        id: "rep-202-1",
        title: "Cabinet hinge adjustment",
        category: "Finish",
        priority: "Low",
        status: "Closed",
        openedAt: "2026-01-04",
        completedAt: "2026-01-05",
        actualCost: 95,
      },
    ],
    maintenance: [
      {
        id: "mnt-202-1",
        title: "Air return cleaning",
        category: "HVAC",
        status: "Upcoming",
        dueAt: "2026-05-01",
      },
    ],
    accessCodes: [
      {
        id: "acc-202-1",
        label: "Apartment keypad",
        accessType: "ApartmentDoor",
        codeLast4: "8834",
        isActive: true,
        effectiveFrom: "2026-01-01",
      },
    ],
    keys: [],
    documents: [],
    notes: [],
  },
  {
    unitCode: "SILVER-C-301",
    propertyCode: "SILVER",
    propertyName: "SilverPines",
    buildingLabel: "C",
    floorLabel: "3",
    unitNumber: "301",
    unitKind: "APARTMENT",
    status: "Turn",
    hasGarage: true,
    garageIndicator: "Y",
    linkedGarageCode: "SILVER-G-03",
    openIssuesCount: 1,
    nextScheduledMaintenance: "2026-03-24",
    lastRepairAt: "2026-03-16",
    lastMaintenanceAt: "2026-03-01",
    ytdRepairCost: 1320,
    notesSummary: "Turn unit. Flooring patch and appliance test in progress.",
    repairs: [
      {
        id: "rep-301-1",
        title: "Dishwasher drainage failure",
        category: "Appliances",
        priority: "High",
        status: "InProgress",
        openedAt: "2026-03-16",
        estimatedCost: 420,
      },
    ],
    maintenance: [
      {
        id: "mnt-301-1",
        title: "Turn checklist closeout",
        category: "Turnover",
        status: "DueSoon",
        dueAt: "2026-03-24",
      },
    ],
    accessCodes: [
      {
        id: "acc-301-1",
        label: "Apartment keypad",
        accessType: "ApartmentDoor",
        codeLast4: "1048",
        isActive: false,
        effectiveFrom: "2025-08-01",
        effectiveTo: "2026-03-12",
        notes: "Prior tenant code deactivated.",
      },
    ],
    keys: [
      {
        id: "key-301-1",
        keyLabel: "Turn crew key set",
        keyType: "Physical",
        assignedTo: "Maintenance team",
        issuedAt: "2026-03-13",
        isActive: true,
      },
    ],
    documents: [
      {
        id: "doc-301-1",
        name: "turn-punchlist-c301.xlsx",
        category: "Spreadsheet",
        mimeType:
          "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        uploadedAt: "2026-03-17",
        sizeLabel: "96 KB",
        summary: "Turn punch list with appliance checks.",
      },
    ],
    notes: ["Do not issue new resident credentials until dishwasher closes."],
  },
  {
    unitCode: "SILVER-C-302",
    propertyCode: "SILVER",
    propertyName: "SilverPines",
    buildingLabel: "C",
    floorLabel: "3",
    unitNumber: "302",
    unitKind: "APARTMENT",
    status: "Occupied",
    hasGarage: false,
    garageIndicator: "N",
    openIssuesCount: 1,
    nextScheduledMaintenance: "2026-03-22",
    lastRepairAt: "2026-03-11",
    lastMaintenanceAt: "2026-01-10",
    ytdRepairCost: 340,
    notesSummary: "Window latch replacement overdue for closeout documentation.",
    repairs: [
      {
        id: "rep-302-1",
        title: "Window latch replacement",
        category: "Hardware",
        priority: "Medium",
        status: "Completed",
        openedAt: "2026-03-09",
        completedAt: "2026-03-11",
        actualCost: 340,
      },
    ],
    maintenance: [
      {
        id: "mnt-302-1",
        title: "GFCI test",
        category: "Safety",
        status: "Overdue",
        dueAt: "2026-03-22",
      },
    ],
    accessCodes: [],
    keys: [],
    documents: [],
    notes: ["Upload completion photo set."],
  },
  {
    unitCode: "SILVER-G-01",
    propertyCode: "SILVER",
    propertyName: "SilverPines",
    buildingLabel: "GAR",
    unitNumber: "01",
    unitKind: "GARAGE",
    status: "Occupied",
    hasGarage: false,
    garageIndicator: "N",
    openIssuesCount: 0,
    lastRepairAt: "2026-01-18",
    ytdRepairCost: 65,
    notesSummary: "Assigned to SILVER-A-101.",
    repairs: [
      {
        id: "rep-g01-1",
        title: "Garage remote battery swap",
        category: "Access",
        priority: "Low",
        status: "Closed",
        openedAt: "2026-01-18",
        completedAt: "2026-01-18",
        actualCost: 65,
      },
    ],
    maintenance: [],
    accessCodes: [
      {
        id: "acc-g01-1",
        label: "Garage keypad",
        accessType: "GarageDoor",
        codeLast4: "4408",
        isActive: true,
        effectiveFrom: "2026-01-01",
      },
    ],
    keys: [],
    documents: [],
    notes: ["Linked to SILVER-A-101."],
  },
  {
    unitCode: "SILVER-G-02",
    propertyCode: "SILVER",
    propertyName: "SilverPines",
    buildingLabel: "GAR",
    unitNumber: "02",
    unitKind: "GARAGE",
    status: "Occupied",
    hasGarage: false,
    garageIndicator: "N",
    openIssuesCount: 0,
    ytdRepairCost: 0,
    notesSummary: "Assigned to SILVER-B-201.",
    repairs: [],
    maintenance: [],
    accessCodes: [],
    keys: [],
    documents: [],
    notes: ["Linked to SILVER-B-201."],
  },
  {
    unitCode: "SILVER-G-03",
    propertyCode: "SILVER",
    propertyName: "SilverPines",
    buildingLabel: "GAR",
    unitNumber: "03",
    unitKind: "GARAGE",
    status: "Occupied",
    hasGarage: false,
    garageIndicator: "N",
    openIssuesCount: 1,
    nextScheduledMaintenance: "2026-03-27",
    ytdRepairCost: 180,
    notesSummary: "Door spring inspection needed.",
    repairs: [
      {
        id: "rep-g03-1",
        title: "Garage door spring noise",
        category: "Mechanical",
        priority: "Medium",
        status: "Scheduled",
        openedAt: "2026-03-16",
        scheduledFor: "2026-03-27",
        estimatedCost: 180,
      },
    ],
    maintenance: [],
    accessCodes: [],
    keys: [],
    documents: [],
    notes: ["Linked to SILVER-C-301."],
  },
  {
    unitCode: "SILVER-G-04",
    propertyCode: "SILVER",
    propertyName: "SilverPines",
    buildingLabel: "GAR",
    unitNumber: "04",
    unitKind: "GARAGE",
    status: "Vacant",
    hasGarage: false,
    garageIndicator: "N",
    openIssuesCount: 0,
    ytdRepairCost: 0,
    notesSummary: "Available for assignment.",
    repairs: [],
    maintenance: [],
    accessCodes: [],
    keys: [],
    documents: [],
    notes: [],
  },
];